title = "Gitleaks custom rules"

[extend]
useDefault = true

[allowlist]
paths = [
  '''node_modules\/''',
  '''vendor\/''',
  '''(.*?)\.rptlibrary''',
  '''package\.json''',
  '''package-lock\.json''',
  '''composer\.json''',
  '''composer\.lock''',
  '''\.gitleaks\.toml$''',
  '''(.*?)(jpg|gif|doc|pdf|bin)$'''
]

regexTarget = "match"
regexes = [
  '''ABCDEFG1234567890'''
]
